[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "autogkb-app"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
loguru = ">=0.7.3,<0.8"
tqdm = ">=4.67.1,<5"
pydantic = ">=2.12.5,<3"
requests = ">=2.32.5,<3"
pandas = ">=2.3.3,<3"
python-dotenv = ">=1.2.1,<2"

[pypi-dependencies]
sentence-transformers = ">=5.2.0, <6"
beautifulsoup4 = ">=4.12.0, <5"
fastapi = ">=0.115.0, <1"
litellm = ">=1.0.0, <2"
uvicorn = {version = ">=0.32.0, <1", extras = ["standard"]}
